# Generated by Django 3.2.5 on 2021-07-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowit_test_app', '0002_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_image',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
    ]
